### PR TITLE
Updated Samples to latest release of Xamarin.Forms

### PR DESCRIPTION
**Pull request by StefanOssendorf**
Updated to Xamarin.Forms v2.3.1.113-pre3

App tested with
- WinPhone Mobile Emulator 10.0.10586.0 WVGA 4 inch 512MB
- 5" Lollipop (5.0) XXHDPI Phone (Android 5.0 - API 21)

Can't test iOS (no Mac available)

### CODE REVIEW

**Comment by brianlagunas** [comment]
I'm releasing the next stable version of Prism soon, so when that happens you can update this PR and I'll merge

**Comment by StefanOssendorf** [comment]
Alright :smiley:

**Comment by StefanOssendorf** [comment]
Updated to Prism 6.2 Release

**Comment by brianlagunas** [comment]
Thanks!

**Comment by StefanOssendorf** [comment]
You're welcome! :)

**Pull request merged**
