### PR TITLE
add more x:DataType to DataTemplates

### PR DESCRIPTION
**Pull request by jmegner**

### CODE REVIEW

**Comment by jmegner** [comment]
Is there anything more needed for this pull request to be satisfactory?

**Comment by brianlagunas** [comment]
This PR has no issues associated with it, and no description describing the purpose of this PR. What exactly are you fixing?

**Comment by jmegner** [comment]
Sorry, this pull request was right after the very similar accepted [pull request 109](https://github.com/PrismLibrary/Prism-Samples-Forms/pull/109).  As the commit says:  add more x:DataType to DataTemplates to get rid of false-alarm messages about binding failures.

A lot of the sample projects will give runtime error messages about binding failures in UWP, but the binding are actually correct.  Adding x:DataType to DataTemplates solves this problem.

**Comment by brianlagunas** [comment]
Thanks for the context, and for the PR

**Comment by jmegner** [comment]
I hope I can contribute even more in the future.  Thanks for Prism, and thanks for all your (@brianlagunas and @dansiegel) help.

**Pull request merged**
